### PR TITLE
Text Improvements: Typos and Grammar Fixes in Chapters 1-8

### PR DESCRIPTION
**Pull request by KennethQNgo**
This pull request provides a review of chapters 1-8 of the documentation, correcting typos, improving grammar, and clarifying several sentences for better readability. These changes are limited to text and do not affect any code or functionality. The goal is to improve the overall quality of the documentation, making it clearer and more consistent.

### CODE REVIEW

**Comment by simongravelle** [comment]
Hi @KennethQNgo, thanks for the correction. Do you want to continue with it or do you want me to merge it? If you want to keep working on this PR, you can simply convert it as "draft", and I will merge it when you convert it back as "non draft".

Also please add your name to the README file as a contributor.

**Comment by KennethQNgo** [comment]
Hey Simon,
I didn't know that was an option! Let's convert it to a draft so I can continue working on it and refine the changes further before it’s ready to merge.
(P.S. Python code working up to chapters 5 for me as well on my end!)

**Comment by simongravelle** [comment]
> (P.S. Python code working up to chapters 5 for me as well on my end!)

Good to hear !

**Comment by simongravelle** [comment]
> I didn't know that was an option! Let's convert it to a draft so I can continue working on it and refine the changes further before it’s ready to merge.

I can't find the option, I think that only you have the option somewhere on this page to convert to draft.

**Comment by simongravelle** [comment]
I just made some restructuring and I am planning to change the name of the Githug repo from MDCourse to MolSimPy for consistency. To avoid future trouble, it would be best to merge that issue. You can re-open a new one.

**Review by simongravelle — APPROVED** [review]
LGTM. Thanks a lot @KennethQNgo for your changes and improvements.

**Pull request merged**
